services:
  sqlServer:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sigele_db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Ch4r4ct3rs"
    ports:
      - "1433:1433"