// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714232858_AddAsistenciaDiaD")]
    partial class AddAsistenciaDiaD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Elector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("Anio")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.Property<string>("Apellido")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("apellido");

                    b.Property<string>("CedApeNom")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ced_ape_nom");

                    b.Property<short?>("CodDist")
                        .HasColumnType("smallint")
                        .HasColumnName("cod_dist");

                    b.Property<short?>("CodDpto")
                        .HasColumnType("smallint")
                        .HasColumnName("cod_dpto");

                    b.Property<short?>("CodigoSec")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_sec");

                    b.Property<short?>("CodigoSex")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_sex");

                    b.Property<string>("Direccion")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("direccion");

                    b.Property<DateOnly?>("FechaAfil")
                        .HasColumnType("date")
                        .HasColumnName("fecha_afil");

                    b.Property<DateOnly?>("FechaNaci")
                        .HasColumnType("date")
                        .HasColumnName("fecha_naci");

                    b.Property<string>("KeyDD")
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .HasColumnName("key_dd")
                        .IsFixedLength();

                    b.Property<short?>("Mesa")
                        .HasColumnType("smallint")
                        .HasColumnName("mesa");

                    b.Property<string>("Nombre")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nombre");

                    b.Property<int>("NumeroCed")
                        .HasColumnType("integer")
                        .HasColumnName("numero_ced");

                    b.Property<short?>("Orden")
                        .HasColumnType("smallint")
                        .HasColumnName("orden");

                    b.Property<short?>("SLocal")
                        .HasColumnType("smallint")
                        .HasColumnName("s_local");

                    b.Property<short?>("SecAnt")
                        .HasColumnType("smallint")
                        .HasColumnName("sec_ant");

                    b.Property<int?>("SecLoc")
                        .HasColumnType("integer")
                        .HasColumnName("sec_loc");

                    b.HasKey("Id")
                        .HasName("pk_elector");

                    b.HasIndex("Apellido")
                        .HasDatabaseName("idx_electores_apellido");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("idx_electores_nombre");

                    b.HasIndex("SecLoc")
                        .HasDatabaseName("ix_elector_sec_loc");

                    b.HasIndex("CodDpto", "CodDist")
                        .HasDatabaseName("idx_electores_dpto_dist");

                    b.HasIndex("CodigoSec", "Mesa")
                        .HasDatabaseName("idx_electores_sec_mesa");

                    b.ToTable("elector", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ElectorConsulta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cedula");

                    b.Property<DateTimeOffset>("ConsultadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consultado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Encontrado")
                        .HasColumnType("boolean")
                        .HasColumnName("encontrado");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("host");

                    b.Property<string>("IpCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_cliente");

                    b.Property<string>("MetodoHttp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("GET")
                        .HasColumnName("metodo_http");

                    b.Property<string>("Origin")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("origin");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_elector_consulta");

                    b.HasIndex("Cedula")
                        .HasDatabaseName("ix_elector_consulta_cedula");

                    b.HasIndex("IpCliente")
                        .HasDatabaseName("ix_elector_consulta_ip_cliente");

                    b.HasIndex("TenantId", "ConsultadoEn")
                        .HasDatabaseName("ix_elector_consulta_tenant_id_consultado_en");

                    b.ToTable("elector_consulta", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LocalVotacion", b =>
                {
                    b.Property<int>("SeccLoc")
                        .HasColumnType("integer")
                        .HasColumnName("secc_loc");

                    b.Property<string>("Direccion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("direccion");

                    b.Property<string>("NombreLoc")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre_loc");

                    b.Property<string>("Recibido")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("recibido")
                        .IsFixedLength();

                    b.HasKey("SeccLoc")
                        .HasName("pk_local_votacion");

                    b.ToTable("local_votacion", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OperadorElector", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("ElectorId")
                        .HasColumnType("integer")
                        .HasColumnName("elector_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DireccionRecogida")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion_recogida");

                    b.Property<bool>("DisponibleMiembroMesa")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible_miembro_mesa");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("NroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nro_telefono");

                    b.Property<int?>("OperadorUbicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("operador_ubicacion_id");

                    b.Property<bool>("RequiereTransporte")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_transporte");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("UserId", "ElectorId")
                        .HasName("pk_operador_elector");

                    b.HasIndex("OperadorUbicacionId")
                        .HasDatabaseName("ix_operador_elector_operador_ubicacion_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_operador_elector_tenant_id");

                    b.HasIndex("UbicacionId")
                        .HasDatabaseName("ix_operador_elector_ubicacion_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_operador_elector_user_id");

                    b.HasIndex("ElectorId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_operador_elector_elector_id_tenant_id")
                        .HasFilter("is_active = true");

                    b.ToTable("operador_elector", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OperadorPersona", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("Cedula")
                        .HasColumnType("integer")
                        .HasColumnName("cedula");

                    b.Property<bool>("Asistio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("asistio");

                    b.Property<DateTimeOffset?>("AsistioMarcadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asistio_marcado_en");

                    b.Property<int?>("AsistioMarcadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("asistio_marcado_por");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DireccionRecogida")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion_recogida");

                    b.Property<bool>("DisponibleMiembroMesa")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible_miembro_mesa");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("NroTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nro_telefono");

                    b.Property<int?>("OperadorUbicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("operador_ubicacion_id");

                    b.Property<bool>("RequiereTransporte")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_transporte");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("UserId", "Cedula")
                        .HasName("pk_operador_persona");

                    b.HasIndex("AsistioMarcadoPor")
                        .HasDatabaseName("ix_operador_persona_asistio_marcado_por");

                    b.HasIndex("OperadorUbicacionId")
                        .HasDatabaseName("ix_operador_persona_operador_ubicacion_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_operador_persona_tenant_id");

                    b.HasIndex("UbicacionId")
                        .HasDatabaseName("ix_operador_persona_ubicacion_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_operador_persona_user_id");

                    b.HasIndex("Cedula", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_operador_persona_cedula_tenant_id")
                        .HasFilter("is_active = true");

                    b.ToTable("operador_persona", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Padron.Persona", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cedula");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cedula"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("apellido");

                    b.Property<DateOnly?>("FecNac")
                        .HasColumnType("date")
                        .HasColumnName("fec_nac");

                    b.Property<string>("Nombre")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("nombre");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origen");

                    b.Property<string>("Sexo")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("sexo");

                    b.HasKey("Cedula")
                        .HasName("ak_persona_cedula");

                    b.HasIndex("Apellido")
                        .HasDatabaseName("idx_persona_apellido");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("idx_persona_nombre");

                    b.ToTable("persona", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Domain.Entities.Padron.RcpDepartamento", b =>
                {
                    b.Property<short>("Depart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("depart");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Depart"));

                    b.Property<string>("Descrip")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("descrip");

                    b.HasKey("Depart")
                        .HasName("pk_departamento");

                    b.ToTable("departamento", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Domain.Entities.Padron.RcpDistrito", b =>
                {
                    b.Property<short>("Depart")
                        .HasColumnType("smallint")
                        .HasColumnName("depart");

                    b.Property<short>("Distrito")
                        .HasColumnType("smallint")
                        .HasColumnName("distrito");

                    b.Property<string>("Descrip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descrip");

                    b.HasKey("Depart", "Distrito")
                        .HasName("pk_distrito");

                    b.ToTable("distrito", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Domain.Entities.Padron.RcpInscripcion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Cedula")
                        .HasColumnType("integer")
                        .HasColumnName("cedula");

                    b.Property<short?>("Depart")
                        .HasColumnType("smallint")
                        .HasColumnName("depart");

                    b.Property<short?>("Distrito")
                        .HasColumnType("smallint")
                        .HasColumnName("distrito");

                    b.Property<DateOnly?>("FecInscri")
                        .HasColumnType("date")
                        .HasColumnName("fec_inscri");

                    b.Property<string>("Interdicto")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("interdicto");

                    b.Property<short?>("Local")
                        .HasColumnType("smallint")
                        .HasColumnName("local");

                    b.Property<string>("Menores")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("menores");

                    b.Property<string>("PolMil")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("pol_mil");

                    b.Property<string>("Tipo")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("tipo");

                    b.Property<short?>("Zona")
                        .HasColumnType("smallint")
                        .HasColumnName("zona");

                    b.HasKey("Id")
                        .HasName("pk_inscripcion");

                    b.HasIndex("Cedula")
                        .HasDatabaseName("ix_inscripcion_cedula");

                    b.HasIndex("Depart", "Distrito", "Zona", "Local")
                        .HasDatabaseName("ix_inscripcion_depart_distrito_zona_local");

                    b.ToTable("inscripcion", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Domain.Entities.Padron.RcpLocalidad", b =>
                {
                    b.Property<short>("Depart")
                        .HasColumnType("smallint")
                        .HasColumnName("depart");

                    b.Property<short>("Distrito")
                        .HasColumnType("smallint")
                        .HasColumnName("distrito");

                    b.Property<short>("Zona")
                        .HasColumnType("smallint")
                        .HasColumnName("zona");

                    b.Property<short>("Local")
                        .HasColumnType("smallint")
                        .HasColumnName("local");

                    b.Property<string>("Descrip")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descrip");

                    b.HasKey("Depart", "Distrito", "Zona", "Local")
                        .HasName("ak_rcp_localidad_depart_distrito_zona_local");

                    b.ToTable("localidad", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Domain.Entities.Padron.RcpZona", b =>
                {
                    b.Property<short>("Depart")
                        .HasColumnType("smallint")
                        .HasColumnName("depart");

                    b.Property<short>("Distrito")
                        .HasColumnType("smallint")
                        .HasColumnName("distrito");

                    b.Property<short>("Zona")
                        .HasColumnType("smallint")
                        .HasColumnName("zona");

                    b.Property<string>("Descrip")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("descrip");

                    b.HasKey("Depart", "Distrito", "Zona")
                        .HasName("ak_rcp_zona_depart_distrito_zona");

                    b.ToTable("zona", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_name");

                    b.ToTable("permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Can read users",
                            Name = "user:read"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Can create operator users",
                            Name = "user:create-operator"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Can create coordinator users",
                            Name = "user:create-coordinator"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_role_name");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Coordinador"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Operador"
                        });
                });

            modelBuilder.Entity("Domain.Entities.SeccLocal", b =>
                {
                    b.Property<short>("CodigoDep")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_dep");

                    b.Property<short>("CodigoDis")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_dis");

                    b.Property<short>("CodigoSec")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_sec");

                    b.Property<short>("CodigoLoc")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_loc");

                    b.Property<short?>("CodLocal")
                        .HasColumnType("smallint")
                        .HasColumnName("cod_local");

                    b.Property<int>("SeccLoc")
                        .HasColumnType("integer")
                        .HasColumnName("secc_loc");

                    b.HasKey("CodigoDep", "CodigoDis", "CodigoSec", "CodigoLoc")
                        .HasName("pk_secc_local");

                    b.HasIndex("SeccLoc")
                        .HasDatabaseName("idx_secc_locales_secc_loc");

                    b.ToTable("secc_local", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seccional", b =>
                {
                    b.Property<short>("CodigoDep")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_dep");

                    b.Property<short>("CodigoDis")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_dis");

                    b.Property<short>("CodigoSec")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_sec");

                    b.Property<string>("Descripcio")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("descripcio");

                    b.Property<string>("Direccion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("direccion");

                    b.Property<string>("NDepart")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("n_depart");

                    b.Property<string>("NDistrito")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("n_distrito");

                    b.Property<string>("WSeccio")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("w_seccio");

                    b.Property<short?>("Zona")
                        .HasColumnType("smallint")
                        .HasColumnName("zona");

                    b.HasKey("CodigoDep", "CodigoDis", "CodigoSec")
                        .HasName("pk_seccional");

                    b.ToTable("seccional", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccessExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_expires_at");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domain");

                    b.Property<int>("ElectorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("elector_count");

                    b.Property<int?>("ElectorLimit")
                        .HasColumnType("integer")
                        .HasColumnName("elector_limit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("OnboardingUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarding_until");

                    b.Property<bool>("SoportaUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("soporta_ubicacion");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subdomain");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_domain")
                        .HasFilter("domain IS NOT NULL");

                    b.HasIndex("Subdomain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_subdomain");

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TenantBranding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("app_title");

                    b.Property<string>("CandidateName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("candidate_name");

                    b.Property<string>("CandidateTitle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("candidate_title");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("favicon_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("primary_color");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("secondary_color");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Zona")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("zona");

                    b.HasKey("Id")
                        .HasName("pk_tenant_branding");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_branding_tenant_id");

                    b.ToTable("tenant_branding", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TenantPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CicloElectoral")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ciclo_electoral");

                    b.Property<int?>("ElectoresAgregados")
                        .HasColumnType("integer")
                        .HasColumnName("electores_agregados");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("package_type");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<DateTime>("PurchasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_package");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_package_tenant_id");

                    b.ToTable("tenant_package", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatetAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createt_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_ubicacion");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ubicacion_tenant_id");

                    b.ToTable("ubicacion", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoordinatorId")
                        .HasColumnType("integer")
                        .HasColumnName("coordinator_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatetAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createt_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("CoordinatorId")
                        .HasDatabaseName("ix_user_coordinator_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_tenant_id");

                    b.HasIndex("Email", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email_tenant_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatetAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createt_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("MontoAlquiler")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_alquiler");

                    b.Property<string>("NombreDueno")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nombre_dueno");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacion");

                    b.Property<int?>("OperadorId")
                        .HasColumnType("integer")
                        .HasColumnName("operador_id");

                    b.Property<string>("TelefonoDueno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono_dueno");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_vehiculo");

                    b.HasIndex("OperadorId")
                        .HasDatabaseName("ix_vehiculo_operador_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_vehiculo_tenant_id");

                    b.ToTable("vehiculo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VehiculoRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprobadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("aprobado_por_id");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatetAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createt_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by");

                    b.Property<int>("ElectorId")
                        .HasColumnType("integer")
                        .HasColumnName("elector_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_resolucion");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MontoAlquiler")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_alquiler");

                    b.Property<string>("NombreDueno")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nombre_dueno");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacion");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer")
                        .HasColumnName("operador_id");

                    b.Property<string>("TelefonoDueno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono_dueno");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_vehiculo_request");

                    b.HasIndex("AprobadoPorId")
                        .HasDatabaseName("ix_vehiculo_request_aprobado_por_id");

                    b.HasIndex("OperadorId")
                        .HasDatabaseName("ix_vehiculo_request_operador_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_vehiculo_request_tenant_id");

                    b.ToTable("vehiculo_request", (string)null);
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<int>("PermissionsId")
                        .HasColumnType("integer")
                        .HasColumnName("permissions_id");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer")
                        .HasColumnName("roles_id");

                    b.HasKey("PermissionsId", "RolesId")
                        .HasName("pk_permission_role");

                    b.HasIndex("RolesId")
                        .HasDatabaseName("ix_permission_role_roles_id");

                    b.ToTable("permission_role", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionsId = 1,
                            RolesId = 1
                        },
                        new
                        {
                            PermissionsId = 2,
                            RolesId = 1
                        },
                        new
                        {
                            PermissionsId = 3,
                            RolesId = 1
                        },
                        new
                        {
                            PermissionsId = 1,
                            RolesId = 2
                        },
                        new
                        {
                            PermissionsId = 2,
                            RolesId = 2
                        },
                        new
                        {
                            PermissionsId = 1,
                            RolesId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Elector", b =>
                {
                    b.HasOne("Domain.Entities.LocalVotacion", "Local")
                        .WithMany("Electores")
                        .HasForeignKey("SecLoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_elector_local_votacion_sec_loc");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("Domain.Entities.ElectorConsulta", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_elector_consulta_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.OperadorElector", b =>
                {
                    b.HasOne("Domain.Entities.Elector", "Elector")
                        .WithMany()
                        .HasForeignKey("ElectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operador_elector_elector_elector_id");

                    b.HasOne("Domain.Entities.Ubicacion", "OperadorUbicacion")
                        .WithMany()
                        .HasForeignKey("OperadorUbicacionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operador_elector_ubicacion_operador_ubicacion_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operador_elector_tenant_tenant_id");

                    b.HasOne("Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operador_elector_ubicacion_ubicacion_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_operador_elector_user_user_id");

                    b.Navigation("Elector");

                    b.Navigation("OperadorUbicacion");

                    b.Navigation("Tenant");

                    b.Navigation("Ubicacion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.OperadorPersona", b =>
                {
                    b.HasOne("Domain.Entities.User", "AsistioMarcadoPorUser")
                        .WithMany()
                        .HasForeignKey("AsistioMarcadoPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operador_persona_user_asistio_marcado_por");

                    b.HasOne("Domain.Entities.Padron.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("Cedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operador_persona_persona_cedula");

                    b.HasOne("Domain.Entities.Ubicacion", "OperadorUbicacion")
                        .WithMany()
                        .HasForeignKey("OperadorUbicacionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operador_persona_ubicacion_operador_ubicacion_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operador_persona_tenant_tenant_id");

                    b.HasOne("Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operador_persona_ubicacion_ubicacion_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_operador_persona_user_user_id");

                    b.Navigation("AsistioMarcadoPorUser");

                    b.Navigation("OperadorUbicacion");

                    b.Navigation("Persona");

                    b.Navigation("Tenant");

                    b.Navigation("Ubicacion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Padron.RcpInscripcion", b =>
                {
                    b.HasOne("Domain.Entities.Padron.Persona", "Persona")
                        .WithMany("Inscripciones")
                        .HasForeignKey("Cedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inscripcion_persona_cedula");

                    b.HasOne("Domain.Entities.Padron.RcpZona", "ZonaNav")
                        .WithMany()
                        .HasForeignKey("Depart", "Distrito", "Zona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inscripcion_rcp_zona_depart_distrito_zona");

                    b.HasOne("Domain.Entities.Padron.RcpLocalidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("Depart", "Distrito", "Zona", "Local")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inscripcion_rcp_localidad_depart_distrito_zona_local");

                    b.Navigation("Localidad");

                    b.Navigation("Persona");

                    b.Navigation("ZonaNav");
                });

            modelBuilder.Entity("Domain.Entities.Padron.RcpLocalidad", b =>
                {
                    b.HasOne("Domain.Entities.Padron.RcpDepartamento", "Dpto")
                        .WithMany()
                        .HasForeignKey("Depart")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_localidad_departamento_depart");

                    b.HasOne("Domain.Entities.Padron.RcpDistrito", "DistNav")
                        .WithMany()
                        .HasForeignKey("Depart", "Distrito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_localidad_distrito_depart_distrito");

                    b.Navigation("DistNav");

                    b.Navigation("Dpto");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.SeccLocal", b =>
                {
                    b.HasOne("Domain.Entities.LocalVotacion", "Local")
                        .WithMany("SeccLocales")
                        .HasForeignKey("SeccLoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_secc_local_local_votacion_secc_loc");

                    b.HasOne("Domain.Entities.Seccional", "Seccional")
                        .WithMany("SeccLocales")
                        .HasForeignKey("CodigoDep", "CodigoDis", "CodigoSec")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_secc_local_seccional_codigo_dep_codigo_dis_codigo_sec");

                    b.Navigation("Local");

                    b.Navigation("Seccional");
                });

            modelBuilder.Entity("Domain.Entities.TenantBranding", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_branding_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.TenantPackage", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_package_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.Ubicacion", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ubicacion_tenant_tenant_id");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.User", "Coordinator")
                        .WithMany("Operators")
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_user_coordinator_id");

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_id");

                    b.HasOne("Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_tenant_tenant_id");

                    b.Navigation("Coordinator");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("Domain.Entities.User", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vehiculo_user_operador_id");

                    b.HasOne("Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculo_tenant_tenant_id");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("Domain.Entities.VehiculoRequest", b =>
                {
                    b.HasOne("Domain.Entities.User", "AprobadoPor")
                        .WithMany()
                        .HasForeignKey("AprobadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vehiculo_request_user_aprobado_por_id");

                    b.HasOne("Domain.Entities.User", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculo_request_user_operador_id");

                    b.HasOne("Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculo_request_tenant_tenant_id");

                    b.Navigation("AprobadoPor");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permission_role_permission_permissions_id");

                    b.HasOne("Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permission_role_role_roles_id");
                });

            modelBuilder.Entity("Domain.Entities.LocalVotacion", b =>
                {
                    b.Navigation("Electores");

                    b.Navigation("SeccLocales");
                });

            modelBuilder.Entity("Domain.Entities.Padron.Persona", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Seccional", b =>
                {
                    b.Navigation("SeccLocales");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Operators");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
